/*-------------------------------------------------------------------------
* Copyright (C) 2018,2019, Esperanto Technologies Inc.
* The copyright to the computer program(s) herein is the
* property of Esperanto Technologies, Inc. All Rights Reserved.
* The program(s) may be used and/or copied only with
* the written permission of Esperanto Technologies and
* in accordance with the terms and conditions stipulated in the
* agreement/contract under which the program(s) have been supplied.
*-------------------------------------------------------------------------
*/

gitlabCommitStatus(name: "${JOB_NAME}") {
    stage("GIT actions") {
        // Explicitely clean things and update specific modules
        sshagent (credentials: ['jennkis_aws_centos']) {
            sh 'rm -rf build'
            sh '${GIT_STEPS}'
        }
    }

    stage("Build Docker") {
        echo "Build Docker"
        // Currently pull the docker image, first review the login credentials
        sh '$(aws ecr get-login --no-include-email --region us-west-1)'
        sh './riscvemu.py --logging=DEBUG docker pull-image et-riscvemu'
    }

    try {
        stage("Build") {
            echo "Build source ${BUILD_STEPS}"
            sh 'rm -rf build'
            sh '${BUILD_STEPS}'
        }

        stage("Test") {
            echo "Build Steps ${TEST_STEPS}"
            sh '${TEST_STEPS}'
        }

    } finally {
        stage("Post Results") {
            echo "Post Test Results"
            final foundFiles = findFiles(glob: "**/build/**/*-test-report.xml")
            for (file in foundFiles) {
                print(file.path)
                junit file.path
            }
        }

        stage("Upload Artifacts") {
            echo "----- $GIT_COMMIT ${GIT_COMMIT} ${env.GIT_COMMIT}"
            sh './riscvemu.py et-riscvemu artifacts.py --push ./artifacts/ et-maxion-ci/${JOB_NAME}/${BUILD_NUMBER}/${GIT_COMMIT}'
        }
    }
}
